### ISSUE TITLE
platform.version gives the version of dart universal_io was compiled under and not what the app was compiled using

### ISSUE THREAD

**Issue by atreeon** [dint-dev/universal_io#10]
If you run platform.version on a mobile app you get the dart version the app was compiled under.  If you run platform.version on the web you get a different dart version (the one universal_io was compiled under).  Both should be displaying the version of dart that the app was compiled under and universal_io is showing the wrong version.

**Comment by terrier989** [comment]
Thanks for the issue report! Platform.version returns an empty string in Javascript and dart:io result elsewhere. I don't think this will be changed.
