### ISSUE TITLE
The InternetAddress.type parameter is missing

### ISSUE THREAD

**Issue by Mabsten** [dint-dev/universal_io#11]
From Dart 2.8, the InternetAddress constructor in `dart:io` has a optional named parameter `InternetAddressType type`, which is missing in universal_io 1.0.1.

Cfr socket.dart in `dart:io`:

```dart
external factory InternetAddress(String address,
      {@Since("2.8") InternetAddressType type});
```

**Comment by terrier989** [comment]
Fixed.
