### ISSUE TITLE
credentialsMode argument missing

### ISSUE THREAD

**Issue by Dark-Shadow-Side** [dint-dev/universal_io#12]
Hi I tried implementing your below example but it says that there is no setter. Please suggest a solution

`
final request = HttpClient().getUrl(Uri.parse('https://example.com/path'));

  if (request is BrowserHttpClientRequest) {
    request.credentialsMode = BrowserHttpClientCredentialsMode.include;
  }

  final response = await request.close();
`

**Comment by wahyu-handayani** [comment]
I have the same problem with you @Dark-Shadow-Side

**Comment by PsychicA** [comment]
> @Dark-Shadow-Side I get the same problem with you and then I am trying this
> 
> ```
>   final httpClient = HttpClient();
>   final request = await httpClient.getUrl(Uri.parse('http://google.com'));
>   if (request is BrowserHttpClientRequest) {
>     request.credentialsMode = BrowserHttpClientCredentialsMode.include;
>   }
> 
>   final response = await request.close();
>   print(response.toString());
> ```
> 
> the error was gone, but I get another error that say like this
> 
> BrowserHttpClient received an error from XMLHttpRequest (which doesn't tell
> reason for the error).
> HTTP method: GET
> URL: http://google.com
> Origin: http://localhost:50768
> Cross-origin request!
> XmlHttpRequest 'credentials mode' is enabled.
> Did the server send the following mandatory headers?
> 
> * Access-Control-Allow-Credentials: true
> * Access-Control-Allow-Origin: http://localhost:50768
>   
>   * In credentials mode, '*' would fail!
> * Access-Control-Allow-Methods: GET
>   
>   * In credentials mode, '*' would fail!
>     Did the server send the following mandatory headers?
> * Access-Control-Allow-Credentials: true
> * Access-Control-Allow-Origin: http://localhost:50768
>   
>   * OR '*'

still i am getting this issue any solution to this?
