### ISSUE TITLE
The multiple set-cookie headers case is not handled properly for browser case

### ISSUE THREAD

**Issue by reeteshranjan** [dint-dev/universal_io#18]
Several flutter libraries including this one don't take care of cases where there are more than set-cookie headers. In fact, not even one of the set-cookie headers is present in the response headers and also in cookies attribute. Things work fine on iOS. I see same behaviour with dart http and dio package.

**Comment by terrier989** [comment]
The behaviour is because browsers prevent scripts from seeing cookie headers.

**Comment by reeteshranjan** [comment]
I had changed my logic meanwhile to look into document.cookie rather than set-cookie response headers. I understand any such workaround is the only way for web.
