### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by long1eu** [dint-dev/universal_io#6]
Awesome job with this package. :D

I'm trying to use it in a nodejs env with Cloud Functions, but I get `window is not defined`. It seems like  `_BrowserHttpOverrides` and such are included. Any ideas on how to overcome this?

**Comment by terrier989** [comment]
Did you try with `import "package:universal_io/prefer_universal/io.dart";`?

**Comment by long1eu** [comment]
actually no, I thought I just need to import the io file in the library root.

**Comment by terrier989** [comment]
The test suite has tests for Node.JS and the `package:universal_io/io.dart` should work. Could you share more information? In what Dart SDK version the error occurs? Is your build.yaml configured for Node.JS? See: https://pub.dev/packages/build_node_compilers

I will add this to the documentation of _nodejs_io_.
