### ISSUE TITLE
Platform.operatingSystemVersion does NOT work

### ISSUE THREAD

**Issue by tomasbaran** [dint-dev/universal_io#9]
it doesn't display anything. It seems it hasn't worked in any of the versions yet.

![WhatsApp Image 2020-07-05 at 14 47 18](https://user-images.githubusercontent.com/25743901/86535633-f8d74d00-bee1-11ea-85b5-425c20eb15cc.jpeg)

**Comment by terrier989** [comment]
Hi! Thanks for the issue report! Currently it returns an empty string. Perhaps it should throw UnimplementedError?

**Comment by terrier989** [comment]
Fixed.
